apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardapio-frontend
  namespace: cardapio
  labels:
    app: cardapio-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: cardapio-frontend
  template:
    metadata:
      labels:
        app: cardapio-frontend
    spec:
      containers:
      - name: cardapio-frontend
        image: node:18-alpine
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://cardapio-backend-service:80/api"
        command: ["sh", "-c", "npm install -g serve && echo 'Frontend temporário' > /tmp/index.html && serve -s /tmp -l 3000"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always 