apiVersion: v1
kind: Secret
metadata:
  name: cardapio-db-secret
  namespace: cardapio
type: Opaque
data:
  # Usando a secret mysql-root-password existente
  # O usu치rio ser치 root e a senha vir치 da secret mysql-root-password
  DB_USER: cm9vdA==  # root
  # A senha ser치 referenciada da secret mysql-root-password existente 