# Traefik Helm Values para Let's Encrypt
# Instalar com: helm install traefik traefik/traefik -f traefik-values.yaml -n traefik-system --create-namespace

# Configurações globais
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Configurações de deployment
deployment:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

# Configurações de ports
ports:
  web:
    port: 80
    expose:
      enabled: true
      exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      enabled: true
      exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

# Configurações de providers
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true

# Configurações de certificados e Let's Encrypt
certificatesResolvers:
  le:
    acme:
      email: admin@546digitalservices.com  # Alterar para seu email
      server: https://acme-v02.api.letsencrypt.org/directory
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

# Configurações de logs
logs:
  general:
    level: INFO
  access:
    enabled: true
    filePath: "/var/log/traefik/access.log"
  file:
    enabled: true
    filePath: "/var/log/traefik/traefik.log"

# Configurações de dashboard
dashboard:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false

# Configurações de segurança
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# Configurações de service account
serviceAccount:
  name: "traefik"

# Configurações de persistence para certificados
persistence:
  enabled: true
  size: 128Mi
  storageClass: ""
  accessMode: ReadWriteOnce
  path: /data

# Configurações de ingress
ingressRoute:
  dashboard:
    enabled: false

# Configurações de middlewares
middlewares:
  default:
    headers:
      frameDeny: true
      sslRedirect: true
      browserXssFilter: true
      contentTypeNosniff: true
      forceSTSHeader: true
      stsIncludeSubdomains: true
      stsPreload: true
      stsSeconds: 31536000
  
  # Middleware para redirecionar HTTP para HTTPS
  redirect-to-https:
    redirectScheme:
      scheme: https
      permanent: true

# Configurações de health check
healthCheck:
  enabled: true

# Configurações de readiness/liveness probes
# Os probes são configurados automaticamente pelo Traefik
